# Generated by Django 4.2 on 2023-07-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile')),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=8)),
                ('job', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('linkedin', models.URLField(max_length=100, verbose_name='linkedin')),
                ('cv', models.FileField(max_length=200, upload_to='cv', verbose_name='cv')),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
