# Generated by Django 4.2 on 2023-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_email_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Employer', 'Employer')], default='', max_length=50, verbose_name='user type'),
            preserve_default=False,
        ),
    ]
