# Generated by Django 4.2 on 2023-04-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slogan', models.CharField(max_length=100, verbose_name='slogan')),
                ('logo', models.CharField(default='logo.png', max_length=50, verbose_name='icon')),
                ('about', models.TextField(max_length=1000, verbose_name='about_us')),
                ('about_image', models.ImageField(upload_to='company', verbose_name='')),
                ('vision', models.TextField(max_length=1000, verbose_name='vision')),
                ('work_days', models.CharField(max_length=250, verbose_name='work_days')),
                ('phones', models.CharField(max_length=300, verbose_name='phones')),
                ('emails', models.CharField(max_length=300, verbose_name='emails')),
                ('Fb_link', models.CharField(max_length=100, verbose_name='icon')),
                ('Gm_link', models.CharField(max_length=100, verbose_name='icon')),
                ('Tw_link', models.CharField(max_length=100, verbose_name='icon')),
                ('Yb_link', models.CharField(max_length=100, verbose_name='icon')),
            ],
        ),
    ]
