# Generated by Django 4.2 on 2023-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('industry', models.CharField(max_length=250, verbose_name='Industry')),
                ('Em_image', models.CharField(max_length=50, verbose_name='Employer_image')),
                ('founded', models.DateField(verbose_name='founded')),
                ('website', models.URLField(verbose_name='website')),
                ('size', models.CharField(max_length=100, verbose_name='company size')),
                ('company_detail', models.TextField(max_length=1000, verbose_name='company detail')),
                ('Em_linkedin', models.URLField(verbose_name='linkedin')),
                ('Em_phone', models.CharField(max_length=50, verbose_name='phone')),
                ('Em_address', models.CharField(max_length=350, verbose_name='address')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
            ],
        ),
    ]
