# Generated by Django 4.2 on 2023-07-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('industry', models.CharField(max_length=250, verbose_name='Industry')),
                ('icon', models.CharField(max_length=50, verbose_name='icon')),
                ('founded', models.DateField(verbose_name='founded')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('website', models.CharField(max_length=150, verbose_name='website')),
                ('size', models.CharField(max_length=100, verbose_name='company size')),
                ('Profile', models.TextField(max_length=1000, verbose_name='company Profile')),
                ('linkedin', models.CharField(max_length=100, verbose_name='linkedin')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
            ],
        ),
    ]
