# Generated by Django 4.2 on 2023-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='Em_image',
            field=models.ImageField(upload_to='Employer'),
        ),
    ]
