# Generated by Django 4.2 on 2023-07-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='size',
            field=models.CharField(max_length=100, verbose_name='company size'),
        ),
    ]
