# Generated by Django 4.2 on 2023-07-08 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='job')),
                ('job_type', models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Remotely', 'Remotely')], max_length=50, verbose_name='job type')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='published at')),
                ('vacancy', models.IntegerField(verbose_name='vacancy')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('des', models.TextField(max_length=2500, verbose_name='description')),
                ('Qual', models.TextField(max_length=2500, verbose_name='Qualifications')),
                ('Res', models.TextField(max_length=2500, verbose_name='Responsibility')),
                ('Benefits', models.TextField(max_length=2500, verbose_name='Benefits')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='board.category', verbose_name='category')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_employer', to='companies.employer', verbose_name='employer')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_author', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('image', models.ImageField(upload_to='Candidates', verbose_name='image')),
                ('linkedin', models.URLField(max_length=100, verbose_name='linkedin')),
                ('cv', models.FileField(max_length=200, upload_to='cv', verbose_name='cv')),
                ('cover', models.TextField(max_length=1000, verbose_name='cover')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='applied_at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_Candidates', to='board.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_Candidates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
