# Generated by Django 4.2 on 2023-04-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.CharField(default='logo.png', max_length=50, verbose_name='icon')),
                ('Fb_link', models.CharField(max_length=100, verbose_name='facebook')),
                ('Gm_link', models.CharField(max_length=100, verbose_name='gmail')),
                ('Tw_link', models.CharField(max_length=100, verbose_name='twitter')),
                ('Yb_link', models.CharField(max_length=100, verbose_name='youtube')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='job', verbose_name='image')),
                ('location', models.CharField(max_length=200, verbose_name='')),
                ('job_type', models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Remotely', 'Remotely')], max_length=50, verbose_name='job_type')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published_at')),
                ('vacancy', models.IntegerField(verbose_name='vacancy')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('description', models.TextField(max_length=2500, verbose_name='description')),
                ('Qualification', models.TextField(max_length=2500, verbose_name='description')),
                ('Responsibility', models.TextField(max_length=2500, verbose_name='Responsibility')),
                ('Benefits', models.TextField(max_length=2500, verbose_name='Benefits')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='board.category', verbose_name='Company')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_company', to='board.job_company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('image', models.ImageField(upload_to='Candidates', verbose_name='image')),
                ('linkedin', models.URLField(max_length=100, verbose_name='linkedin')),
                ('cv', models.FileField(max_length=200, upload_to=None, verbose_name='cv')),
                ('cover', models.TextField(max_length=1000, verbose_name='cover')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='applied_at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_Candidates', to='board.job')),
            ],
        ),
    ]
