# Generated by Django 4.2 on 2023-07-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
    ]
