# Generated by Django 4.2 on 2023-04-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterField(
            model_name='candidates',
            name='cv',
            field=models.FileField(max_length=200, upload_to='cv', verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, verbose_name='location'),
        ),
    ]
