# Generated by Django 4.2 on 2023-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
