# Generated by Django 3.2 on 2023-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='Apply_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
