# Generated by Django 3.2 on 2023-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_apply_job_apply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='img',
            field=models.ImageField(default='', upload_to='Apply_job/'),
            preserve_default=False,
        ),
    ]
